clone:
  path: github.com/drone/drone-exec

build:
  image: armhfbuild/golang:1.5
  environment:
    - GOPATH=/drone
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - go get github.com/franela/goblin
    - go get ./...
    - go test ./...
    - go build

publish:
  docker_master:
    image: armhfplugins/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/drone-exec
    tag:
      - latest
    when:
      repo: armhf-docker-library/drone-exec
      branch: master

  docker_branch:
    image: armhfplugins/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/drone-exec
    tag: $$BRANCH
    when:
      repo: armhf-docker-library/drone-exec

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
