
build:
  image: armhfbuild/golang:1.5
  environment:
    - GOPATH=/drone
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - go get github.com/franela/goblin
    - go get ./...
    - go test ./...
    - go build

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/drone-exec
    storage_driver: overlay
    when:
      branch: master
